### ISSUE TITLE
How to change GridSeed 5 miners' frequency in MultiMiner

### ISSUE THREAD

**Issue by Clearik** [nwoolls/MultiMiner#195]
Hello all, I currently have a small LTC mining operation going with 6 GridSeed 5 miners. I'm using MultiMiner as my mining program, which I'm sure you all know is just a GUI for BFGMiner. From my understanding, in order to send commands to BFGMiner, you have to go Settings -> Advanced Miner Setting -> Change "Arguments" to Scrypt -> Type in the code to send to BFGMiner

What is the code to change the frequency of the miners? I've tried many things, and what I currently have set is "gridseed -S gridseed:all --set-device gridseed:clock=800" (without the quotes), which obviously isn't working. I've also tried "--set-device gridseed:clock=800" and "--set- gridseed:clock=800" with no success.

I think the problem may be the "gridseed" part of the code. That's the name of the "driver" in MultiMiner, however I have each miner named differently. Also, when I click on a device for more information, it says "STM32 Virtual COM Port", which I believe is the original driver it attempted to use.

With that all being said, I'm at a loss. I'm getting roughly 250KH/s per miner when I should be getting around 350KH/s per miner, so I really need to change the frequency. 

Thank you all for your time and consideration.

-Clearik

**Comment by nwoolls** [comment]
Please find documentation for this feature here. You may need to consult the BFGMiner documentation or GridSeed documentation for exact syntax.

https://github.com/nwoolls/MultiMiner/wiki/Overclocking#overclocking
https://github.com/luke-jr/bfgminer/blob/bfgminer/README.ASIC

FWIW ```--set-device gridseed:clock=800``` should work just fine.

**Comment by Clearik** [comment]
I'll try all of this as soon as I get back to my mining rig. Thank you very much nwoolls for taking time out of your day to help me.

**Comment by nwoolls** [comment]
My pleasure - the Overclocking page has a screenshot that includes my working settings.

**Comment by Clearik** [comment]
Hmm, I notice you have:
 
--set gsd:clock=835 -I 17

without the -device

Is that unneeded, or does the "gsd" replace the "-device"?

I'm sorry for my utter ignorance on the subject of programming, I am trying to learn though.

**Comment by nwoolls** [comment]
```--set``` is just short-hand for ```--set-device``` and likewise "gsd" is short-hand for "gridseed". Either will work in both cases.

**Comment by Clearik** [comment]
Oh okay, thanks, I really appreciate it. It's awesome of you to make this program so easy-to-use. It really opens the doors for programming illiterate people like me. 

I'll let you know if it works as soon as I get back to my rig, so that we can close this thread.

Thanks again!

**Comment by Clearik** [comment]
Hello, I've finally had a chance to get to my mining rig. Here are my current settings after about 30 minutes of continual mining:
![capture2](https://cloud.githubusercontent.com/assets/10477432/5693465/de9fa710-98eb-11e4-9da6-f4aee25fbfc0.PNG)
and here are the results:
![capture](https://cloud.githubusercontent.com/assets/10477432/5693468/ef82e2fe-98eb-11e4-9ce2-43fe6503392c.PNG)
The "Effective" rate will occasionally jump to about 350KH/s on different devices, but only momentarily. If I've researched correctly, the hashrate should be about 350KH/s per device at 800MHz, right?

I don't mean to keep bugging you, I just feel like I'm doing something wrong.

If you need any info whatsoever, I'll be happy to supply it. Thank you again nwoolls!

**Comment by nwoolls** [comment]
I get 345 Kh/s with ```--set gsd:clock=835``` as shown in the screenshots. I do not get 350 Kh/s at 800 MHz.

**Comment by Clearik** [comment]
I have just stopped the devices, inserted --set gsd:clock=835 for the argument, and have restarted the devices. I will let them run until tomorrow, and then post the results. Thanks again for your help, have a good night!

-Clearik

**Comment by Clearik** [comment]
Hello again nwoolls, I hope your weekend went well. Here are my following settings after letting the mining rig run about half a day:

![capture2](https://cloud.githubusercontent.com/assets/10477432/5697809/90e484c6-99c9-11e4-85ba-3357fdc1ab1f.PNG)

![capture3](https://cloud.githubusercontent.com/assets/10477432/5697810/94a8bf64-99c9-11e4-9da3-99d8624fd3ba.PNG)

and the following are the results:

![capture](https://cloud.githubusercontent.com/assets/10477432/5697812/9e576b78-99c9-11e4-9f9c-b64ec7ee5985.PNG)

Unfortunately, still not quite right. Are there perhaps other settings that I have incorrect? Perhaps my miners are not getting enough power? I have them powered via Molex from a dedicated 600W PSU. Or could possibly the devices themselves all be malfunctioning? I'm at quite a loss.

Also, this may be a foolish question, but what rate am I truly concerned with? The "Current" rate or the "Effective" rate?

Thank you again so much for your time and consideration. If you are too busy throughout the week to respond, that's okay, I can wait until the weekend.

-Clearik

**Comment by nwoolls** [comment]
Effective hash-rate is what the pool is considering, so this is the more important number.

I am not sure why the units are not accepting the over-clocking arguments. I do not see anything obviously wrong with your setup. I am not having that issue with my own Orbs, G-Blades or G-Blacks so I am at a loss.

If you think it may be a power issue try with just 1 Orb to start.

**Comment by Clearik** [comment]
Hey nwoolls, I hope your week is going well. 

Do you know if maybe there is anyway I could "hide" the the MultiMiner GUI, insert the commands to BFGMiner, then "unhide" the MultiMiner GUI?

I love MultiMiner, it's just perfect, but I just need to get this one issue resolved.

Thank you again for all of your help and consideration.

-Clearik

**Comment by Fr0z7y** [comment]
i'ld like to say that even though this is how you do it, as in settings for the gridseed under advanced settings, if you have already setup your pool information for litecoin and have been mining with it, there tends to be a small issue that won't allow your pools that you have already setup for gridseeds/scrypt algorithms to mine at that frequency. i had this problem, too, and have been beating my head against the wall trying to fix it. i just left the scrypt code in there and have added new pools for different coins for scrypt (they are multipools, and the name of the coin doesnt matter as long as you know the information that is there and don't mind the difficulty, price, profitability sections being wrong) because of the low hash rate i was getting from the gridseeds i figured i would try mining some other coins as well, and when i did put those other pools in for scrypt, the hash rate on my miners jumped to between 350 - 364 kh/s for current and average, although effective bounces around a bit. i then went and added a new coin for scrypt and put all my litecoin pool information into that coins addresses, and it worked for those pools i was previously getting low hash rates on. i'm not sure why it does that, but if you are having this issue, this might help you.

after you have already put in the gridseed clock settings for scrypt algo's, make a new scrypt altcoin with all of your settings (you could probably delete your old litecoin one if you wanted to redo a litecoin one) and try it out, it should work. that's what i did, and it's working perfectly for me.

**Comment by nwoolls** [comment]
Closing - no known issue here. These arguments are passed to the underlying miner. Please reopen if there is an issue in the current release.
