### ISSUE TITLE
MultiMiner does not find USB Antminer U3 v2

### ISSUE THREAD

**Issue by jakerich** [nwoolls/MultiMiner#226]
I have two USB Antminer U3 v2's connected to my workstation. MultiMiner cannot find them. I am able to use them with CGMiner, but I prefer MultiMiner. Are there any settings I can change to get them to work with MultiMiner?

**Comment by nwoolls** [comment]
You will need to wait for a release of BFGMiner that supports the AntMiner U3. MultiMiner uses BFGMiner for ASIC mining rather than CGMiner due to wider ASIC support.

Until then you can run CGMiner with the ```--api-allow``` and ```--api-listen``` arguments and MultiMiner should show the device after a few minutes under the Network group. You can find more info here:

https://github.com/nwoolls/MultiMiner/wiki/Network-Devices#network-devices

**Comment by jakerich** [comment]
Ok thank you. I will have to use CGMiner for now. I hope BFGMiner supports the U3's soon. I prefer to donate 3% to 5% of my hashes using MultiMiner but for now I cannot :( thank you for your help!

Jake
