### ISSUE TITLE
Multiminer dosent detect ''Coin to add''  Help please

### ISSUE THREAD

**Issue by Lysbakken** [nwoolls/MultiMiner#256]
Hello there miners :) Im trying to mine Bitcoins. I choosed SHA256, but below there is suppost to be the currency list. But on my computer these is just a blank there, i have been trying to put it ''Bitcoin'' and ''BTC'' But Multiminer just wont start it up and im getting a error ''Launching Miner Failed
none of the pools configured for ''Bitcoin'' could be used. Verify your pool settings and try again.'' 
I would really like some help here, and i might be doing a silly mistake Thanks!

Sorry for scrapy english... 👎

**Comment by hidarneh** [comment]
i have this problem . nobody can help?

**Comment by nwoolls** [comment]
The empty drop down is because the default Coin API - CoinChoose - is no longer up. Either install the latest version of MultiMiner (which changes the default) or use the [Online Service Settings](https://github.com/nwoolls/MultiMiner/wiki/Settings#online-service-settings) screen to pick a functional Coin API such as WhatToMine.

If problems persist enable the option to "Display API error notifications" in the [Advanced Service Settings](https://github.com/nwoolls/MultiMiner/wiki/Settings#advanced-service-settings).
