### ISSUE TITLE
MultiMiner-4.1.1.app.zip is corrupt 

### ISSUE THREAD

**Issue by qcha0s** [nwoolls/MultiMiner#291]
On macOS it prompts for an admin password but still fails to open.

**Comment by nwoolls** [comment]
Try a different browser, an incognito window, or a different program for unzipping. I just tried the download on two different systems, with both the CLI `unzip` utility as well as the default Archive Utility, and had no problems whatsoever.

**Comment by qcha0s** [comment]
Umm ... no, its still corrupt. Firefox, Chrome & Safari. 
Multiple downloads ... all corrupt. 


![screen shot 2017-11-15 at 8 15 20 am](https://user-images.githubusercontent.com/717986/32838043-b684048a-c9dd-11e7-9f9d-c6a5762e3945.png)
<img width="977" alt="screen shot 2017-11-15 at 8 18 25 am" src="https://user-images.githubusercontent.com/717986/32838051-bf74ba6c-c9dd-11e7-8c16-26f545fe18ac.png">

**Comment by nwoolls** [comment]
@qcha0s I'm sorry to hear that but I assure you the problem is not with the zip file. Again I (and many others) have already successfully downloaded and unzipped it. I myself have verified it using four different PCs, on two different networks, and with three different browsers.

There is something unique to your setup causing this issue. Either something related to the network, some firewall or Anti-Virus configuration, etc.

**Comment by nwoolls** [comment]
@qcha0s double-check the hash as well:

```
shasum MultiMiner-4.1.1.app.zip
bfcb9a249c3f117bb34f49be2889865576c9974d  MultiMiner-4.1.1.app.zip
```

It should be `bfcb9a249c3f117bb34f49be2889865576c9974d` as above. Otherwise your download is getting corrupted.
