### ISSUE TITLE
Network miners

### ISSUE THREAD

**Issue by tutorialevideo** [nwoolls/MultiMiner#320]
I tryed to scan the network miners but no luck tested on 2 diff PC-s with win 10 64 bits any sugetion?

**Comment by nwoolls** [comment]
What miners are these? Are the miners on your local network? What are some example IPs?

Check the documentation here:

* https://github.com/nwoolls/MultiMiner/wiki/Network-Devices

Specifically ensure your miners are configured properly and that the `RPC-API-Test` succeeds. There are also options under *Advanced Application Settings* for determining what IPs are scanned:

* https://github.com/nwoolls/MultiMiner/wiki/Settings#advanced-application-settings

You can also manually edit `NetworkDevicesConfiguration.xml` in the settings folder (`%appdata%\MultiMiner` on Windows, `~/.config/MultiMiner/` otherwise) to add / update entries with the format:

```
  <NetworkDevice>
    <IPAddress>192.168.0.XYZ</IPAddress>
    <Port>4028</Port>
    <Sticky>true</Sticky>
    <Hidden>false</Hidden>
    <RecentCommands />
  </NetworkDevice>
```

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
