### ISSUE TITLE
 How can I add the algorithm X16R?

### ISSUE THREAD

**Issue by jmh77777** [nwoolls/MultiMiner#324]
Does anyone know about the GPU algorithm  X16R and can give me some more info about it, etc.

Thanks

**Comment by nwoolls** [comment]
You can find information on adding GPU algorithms and backend miners on the wiki:

* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms
* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners

If you would like to discuss mining and algorithms (rather than reporting specific issues) I would recommend using a discussion forum.
