### ISSUE TITLE
Ransomware behaviour

### ISSUE THREAD

**Issue by Ollie2018EA** [nwoolls/MultiMiner#376]
My antivirus blocked both the download, installation and use of the application because ransomware behavior was found and as soon as I started using it, it tried infecting additional files that had nothing to do with the program itself. I have logs and remediation action logs from my antivirus Bitdefender. You might say that it is not malicious but according to Bitdefender, it dam is. I have even contacted Bitdefender and they have told me that it is malicious and they have had previous reports of it.
![image](https://user-images.githubusercontent.com/47368790/54836275-ca693a80-4cbb-11e9-8155-68349cfa7734.png)
![image](https://user-images.githubusercontent.com/47368790/54836639-8f1b3b80-4cbc-11e9-8c07-15fabc196eae.png)
![image](https://user-images.githubusercontent.com/47368790/54836664-9cd0c100-4cbc-11e9-8caf-4b5b1dfeb413.png)
![image](https://user-images.githubusercontent.com/47368790/54836319-df45ce00-4cbb-11e9-82f9-61fefacbba6c.png)
![image](https://user-images.githubusercontent.com/47368790/54836361-f1c00780-4cbb-11e9-8fc8-d18087d41eb4.png)
![image](https://user-images.githubusercontent.com/47368790/54836391-043a4100-4cbc-11e9-897e-0091b7091390.png)

Bitdefender has never failed me in the 3 years I have used it. I do have Bitdefender to back me up on this malicious behavior and I have reported it to GitHub for investigation.

What I would like to know is why is it that it is trying to make changes to other files and hijacking other programs? All the other users I have heard using it have had no problems.

**Conversation with Bitdefender about hijacking other applications:**
March 22, 2019, 11:11 am - XXXXX XXXXXX : Oh, and my autocad software is also malware as well
March 22, 2019, 11:12 am - XXXXX XXXXXX : According to Bitdefender
March 22, 2019, 11:13 am - Dana Popa : It is a program that creates programs as well?
March 22, 2019, 11:13 am - XXXXX XXXXXX : It's 3D software, only comes up as malware after I downloaded the 'virus', could it of infected it?
March 22, 2019, 11:15 am - Dana Popa : Yes, it may have. Mining application are known for exploiting other application from the device.

**Comment by KI5JYD** [comment]
@Ollie2018EA WTF are you talking about??? Antivirus is a scam. Delete Bitdefender **now**.

**Comment by Ollie2018EA** [comment]
Eh...NO! My AV is not a scam. Bitdefender has over 500 MILLION USERS.

**Comment by ThatSkepticalGamer** [comment]
@Ollie2018EA  I'm not going to say that paid AV's are scams. However, Multiminer is not malware, AV's just say so. Let me explain; because crypto mining can make you money, malicious hackers usually install crypto miners on their victims' PC, and send the profit to their own crypto wallet. Because of this, most AV's mark all miners as malicious (https://www.reddit.com/r/MoneroMining/comments/88bwjq/why_are_miner_software_flagged_as_malware/). Also, the "Protected File" Multi Changed was your Desktop. Not that important, and there may be a good reason for it. The Bitdefender employee is either a moron, or you made them up. I and everybody else on this Github have had zero malware problems. I also highly doubt it affected AutoCAD. Make sure you are downloading it from the official source, and not Sourceforge or Softonic or anything. BTW, don't trust Bitdefender just because it has alot of users, and consider disabling Bitdefender and running a scan with a different AV to see how the results differ.

**Comment by nwoolls** [comment]
Couldn't have said it better than @ThatSkepticalGamer - AV flags legitimate mining software as malware due to its rampant use in malware. If you are concerned about the behavior of MultiMiner, the source is in this repo and you can build from that source instead of running the downloaded executable.

**Comment by Lo-Tek** [comment]
I downloaded the MultiMiner-4.3.1.exe from the release pages and my windows AV twice now after trying to run the program flags it as a trojan. Regardless of who did what or if AV is a scam or not I believe there is a trojan attached to the exe.
![multiminer](https://user-images.githubusercontent.com/77877457/120025726-f96b4d00-bfa5-11eb-9989-c3ac9958c74e.png)
